### ISSUE TITLE
High Resolution Capture Fails with H.264

### ISSUE THREAD

**Issue by filibis** [keijiro/FFmpegOut#11]
Hi @keijiro , first of all thank you for this great script, it's working nicely except below issue.

---
**Resolutions higher than full-hd (1920x1080) causes error with H.264.** It exports the .mp4 to the folder, size looks reasonable but video can't be played and resolution of video is blank. I tried enable/disable 'Set Resolution' tickbox or change it via script but nothing worked (Everything works okay with ProRes). Is that a technical inability of the codec, thus can't be overcome?

Here are 2 different errors i get on different captures:

> ffmpeg returned with a warning or an error message. See the following lines for details:
> [swscaler @ 000000000035cfa0] Warning: data is not aligned! This can lead to a speedloss
> 
> UnityEngine.Debug:LogWarning(Object)
> FFmpegOut.CameraCapture:ClosePipe() (at Assets/FFmpegOut/CameraCapture.cs:177)
> FFmpegOut.CameraCapture:Update() (at Assets/FFmpegOut/CameraCapture.cs:83)
---
> ffmpeg returned with a warning or an error message. See the following lines for details:
> [libx264 @ 000000000071cb40] frame MB size (320x180) > level limit (36864)
> [libx264 @ 000000000071cb40] DPB size (4 frames, 230400 mbs) > level limit (3 frames, 184320 mbs)
> 
> UnityEngine.Debug:LogWarning(Object)
> FFmpegOut.CameraCapture:ClosePipe() (at Assets/FFmpegOut/CameraCapture.cs:177)
> FFmpegOut.CameraCapture:Update() (at Assets/FFmpegOut/CameraCapture.cs:83)

**Comment by keijiro** [comment]
I suppose that this issue doesn't reproduce with the latest version.

https://github.com/keijiro/FFmpegOut/releases/tag/v1.0.0

I'm closing this ticket. Please feel free to reopen if it still reproduces.
