### ISSUE TITLE
Streaming

### ISSUE THREAD

**Issue by sinokgr** [keijiro/FFmpegOut#12]
Hi there,
thanks for sharing the code. It was really helpful for my project. I tried to make it stream to an IP but I couldn't do it. Do you think you can add streaming support?
Cheers,
Nick

**Comment by keijiro** [comment]
FFmpegOut is designed for offline (non-realtime) rendering. I don't think that it's capable of real time streaming.

I'm closing this issue. Please feel free to reopen if you have further questions.

**Comment by sinokgr** [comment]
Based on [their](https://trac.ffmpeg.org/wiki/StreamingGuide) documentation, they support streaming. Do you think you could help?

**Comment by keijiro** [comment]
Technically it could, but it needs several efforts to add streaming support to FFmpegOut and make it stable.

Personally I think using Spout and a bridge server (like TCPSpout) is a better solution.

https://github.com/keijiro/KlakSpout
http://techlife.sg/TCPSpout/

**Comment by sinokgr** [comment]
great, thanks for the suggestion. I'll have a look to the links you posted. 👍

**Comment by sinokgr** [comment]
Hi @keijiro , I gave your suggestion a go and it works great for streaming from one PC to the other. What I wanted to do though, was streaming from one PC to browsers on web.

**Comment by keijiro** [comment]
If you mean "from one PC to browser on another PC" (1 to 1), streaming with ffmpeg is probably helpful.

If you're trying broadcasting (1 to many), I think it never works.

**Comment by sinokgr** [comment]
what I want to do, is to have unity running to a public PC, and have a browser stream the camera in the html. My understanding was that I would have unity running streaming to "a" server and then when I point a video tag to this server IP, it would display the same content with Unity.

**Comment by keijiro** [comment]
It could work if you have enough bandwidth. I recommend calculating the required bandwidth before starting R&D.

**Comment by sinokgr** [comment]
I know it was done before (not sure if it was with FFmpeg or a different technology) but it works. I've seen the existing solution running on phone and on PC and I saw a varied experience. Some times it was very slow some times it was fine. But it should be similar to streaming you webcam on web. I wouldn't expect to get 90fps, but even 25 in my case would be enough.

**Comment by keijiro** [comment]
Sounds good. Go ahead and good luck! Unfortunately I don't have enough time for helping you out (I estimated that it needs lots of time for R&D, so that I can't make it), but I hope you make good progress on it.

**Comment by sinokgr** [comment]
thanks for your time 👍
