### ISSUE TITLE
Trouble with depth buffer

### ISSUE THREAD

**Issue by AMCB** [keijiro/FFmpegOut#16]
Hi @keijiro, first thank you for your wonderful work!

I have some strange result when rendering with the Camera-Capture : it looks like the Z-buffer is corrupted.
Here is a sample : on the left, normal rendering, on the right when I activate the Camera-Capture script.
<img width="610" alt="bugcameracapture" src="https://user-images.githubusercontent.com/4648713/30786604-c20bd0a4-a178-11e7-8513-15aa45164e04.png">
It seems back-faces are sometimes renderer after and in front of other faces.

Just let me know if you need to have access to my project.

Regards,
Adrien

**Comment by keijiro** [comment]
Thanks for reporting. I need to reproduce the issue on my side. Could you provide a small project that can reproduce the issue?

**Comment by AMCB** [comment]
Hi Keiijiro,
Here is my test project : http://gofile.me/3A2wI/wlKF0ItlG
I have the same result on my Macbook Pro or my Hackintosh. If it can help investigating the funnel-syphon asset you created works as expected, without any issue.
Regards,
Adrien

**Comment by AMCB** [comment]
After a quick check, it works normally on Windows. The bug on rendering is only OS X.

**Comment by keijiro** [comment]
I guess that this issue is relevant to the bug that I fixed in the latest version (v0.1.2).

https://github.com/keijiro/FFmpegOut/releases

Please give a try to this latest version.

**Comment by keijiro** [comment]
I'm closing this issue. Feel free to reopen for further problems.

**Comment by AMCB** [comment]
Thanks a lot, it works perfectly!!
