### ISSUE TITLE
请问那个shader是如何赋值的？我没有看到shader初始化的语句啊！

### ISSUE THREAD

**Issue by Thomas-JZQ** [keijiro/FFmpegOut#17]
请问“CameraCapture.cs”中的“[SerializeField, HideInInspector] Shader _shader;”这句话中，这个_shader是如何初始化的？我都没有在脚本中看到初始化的语句，但运行起来确实是正常赋值的。请教一下，这个是怎么实现的呢？

**Comment by Thomas-JZQ** [comment]
I am sorry，i should ask questions by English. My question is how to assigning variables for "_shader"？There is “[SerializeField, HideInInspector] Shader _shader;” in “CameraCapture.cs” script, your script is great, everyting goes well in runtime,but i do not know why the value of  variable "_shader" is not "null"?

**Comment by keijiro** [comment]
Because the default value is set in the meta info.

https://github.com/keijiro/FFmpegOut/blob/master/Assets/FFmpegOut/CameraCapture.cs.meta#L8

You can change the default value from the inspector (select the script, then check the inspector).

**Comment by Thomas-JZQ** [comment]
thank you
