### ISSUE TITLE
What's wrong! I can capture nothing except skybox? 

### ISSUE THREAD

**Issue by Thomas-JZQ** [keijiro/FFmpegOut#18]
I build a simple scene in Unity2017.1.0f3 to test capture something ,but when capture started,the camera renderering nothing except skybox,finally i only have a skybox vedio.What happened?What should i do?
The attachment is the simple scene,please take a look at it when you have free time,thank you!
[CaptureTestScene.zip](https://github.com/keijiro/FFmpegOut/files/1361490/CaptureTestScene.zip)

**Comment by keijiro** [comment]
Nice catch. I found a small but critical bug in the camera capture component.

The bug has been already fixed. Please try v0.1.2.

https://github.com/keijiro/FFmpegOut/releases

I'm closing this issue. Please feel free to reopen if you find further issues.

**Comment by Thomas-JZQ** [comment]
thank you！！！
