### ISSUE TITLE
Video is half in length and fast motion.

### ISSUE THREAD

**Issue by egeaydin** [keijiro/FFmpegOut#21]
Every time I record, the video output is half in length, if I say 50 seconds, the video is 25 seconds, and also it is accelerated. I am not sure what causing this? Any idea?

**Comment by keijiro** [comment]
Do you enable "Allow Slow Down" property in the Camera Capture component?

**Comment by egeaydin** [comment]
Thanks for the answer. With that enabled, it seems like it is always one second less now, but it is still faster than the usual.

**Comment by oogie-boogie** [comment]
Sorry for kind of necroing this, but i'm having the same issue even with slowdown. I'm currently trying to solve it but haven't reached a solution yet. Any extra info on the issue would be nice.
Thanks

**Comment by keijiro** [comment]
The frame rate controlling logic was completely rewritten in the latest update. I suppose that this issue doesn't reproduce any more.

https://github.com/keijiro/FFmpegOut/releases/tag/v1.0.0

I'm closing this ticket. Please feel free to reopen if it still reproduces.
