### ISSUE TITLE
Render Texture Anti-aliasing 

### ISSUE THREAD

**Issue by noelmkawano** [keijiro/FFmpegOut#22]
Hi Keijiro. Nice job on this plugin! However I noticed that there is a drop in quality for line objects once recording starts. I was able to fix this by adding this line after you define _tempTarget in CameraCapture.cs:
_tempTarget.antiAliasing = 8;

I hope this helps!

**Comment by keijiro** [comment]
Yes, it should support MSAA. I'll check it later.

**Comment by keijiro** [comment]
It's finally fixed in v1.0.1.
