### ISSUE TITLE
Multi camera

### ISSUE THREAD

**Issue by A7ocin** [keijiro/FFmpegOut#23]
Hi, is there a way to capture videos from multiple cameras in the scene at the same time?
Thanks

**Comment by keijiro** [comment]
You can use multiple CameraCapture components simultaneously, so simply add CameraCapture to each camera.

**Comment by A7ocin** [comment]
I already tried, but unfortunately it doesn't work

**Comment by keijiro** [comment]
Hmm, weird. I often use multiple cameras with ffmpegout.

How doesn't it work? Does it output only a single file? Or some of them are broken?

**Comment by A7ocin** [comment]
Hi again,
I think I found out the issue. I was adding the script to three cameras which were children of a prefab GameObject. I think that's why the script wasn't able to record the videos correctly.

By attaching the script to three other cameras it worked, thanks.

**Comment by keijiro** [comment]
Huh, okay. Thanks for clarification.
