### ISSUE TITLE
Getting Audio

### ISSUE THREAD

**Issue by JelleDekkers** [keijiro/FFmpegOut#26]
Is it possible to get audio alongside video?  If so, how?

**Comment by keijiro** [comment]
Please see #25. Also I'd recommend using [Recorder](https://assetstore.unity.com/packages/essentials/unity-recorder-94079).

**Comment by keijiro** [comment]
I'm closing this issue. Please feel free to reopen for further questions.

**Comment by JelleDekkers** [comment]
Ah sorry about that, I forgot to look at the closed issues. That's a shame. We're using this to livestream Unity, which is working perfectly. Unfortunately we also need audio.
