### ISSUE TITLE
HDRP support?

### ISSUE THREAD

**Issue by kocosman** [keijiro/FFmpegOut#28]
While recording in HDRP, the game view only shows the skybox, and the recorded file is 1kb.  Will there be HDRP support?

**Comment by keijiro** [comment]
I'm thinking of adding SRP support but don't have time for it. At the moment, it's recommended to use [Unity Recorder](https://assetstore.unity.com/packages/essentials/unity-recorder-94079) instead.

**Comment by keijiro** [comment]
HDRP support was added in the latest version.

https://github.com/keijiro/FFmpegOut/releases/tag/v1.0.0

**Comment by keijiro** [comment]
I'm closing this issue. Please feel free to reopen for further questions.
