### ISSUE TITLE
Android Binary's?

### ISSUE THREAD

**Issue by Benjamesin** [keijiro/FFmpegOut#32]
Is it possible to use android binary's with FFmpegOut?

 I attempted to detect if platform is android then changed the executable path to binary's that i found elsewhere. This did not work, but maybe it can work and i'm not doing something right.

**Comment by keijiro** [comment]
I don't have much experience on Android app development, so I have no idea about what's happening in it.

I'm closing this issue now. Please feel free to reopen it for further questions.
