### ISSUE TITLE
Read while writing

### ISSUE THREAD

**Issue by FrankMiller9000** [keijiro/FFmpegOut#35]
Hi I am trying to read the video -- ie stream to other "clients" while it is being "written to", is this a windows permission issue or is something to do with the code, ie it seems like the only way I can actually read the file is after its closed.

Okay I tried it on mac and the same issue. Is the video not a video until after it closes and does whatever it needs to, is there any easy way to change this?

**Comment by keijiro** [comment]
You can't use a common file for streaming like that. You have to use inter-process communication like named pipe or local network streaming. Unfortunately, there is no easy way to implement it -- you may have to invest some time to implement it.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further questions.
