### ISSUE TITLE
UI-Screen Space Overlay not included in render texture

### ISSUE THREAD

**Issue by TeapoyYinYue** [keijiro/FFmpegOut#38]
We are currently developing an application using HDRP and using UI setting of Screen Space Overlay.
Although the UI is not included in the render texture under this setting, we have to use this setting in order for the UI to work in HDRP.
We also need to record the UI, but it is not recorded.
We are also using this recording feature in a build, so I suppose Unity Recorder would not be an option.
Does anyone have a easy way to work around this issue or this is a dead-end?

**Comment by keijiro** [comment]
Your understanding is right. There is no easy workaround. You have to use "Screen Space - Camera" mode instead.

**Comment by keijiro** [comment]
I'm closing the issue now. Please feel free to reopen for further problems.
