### ISSUE TITLE
Manually calling PushFrame

### ISSUE THREAD

**Issue by sam598** [keijiro/FFmpegOut#39]
Hi Keijiro!

This plugin is extremely helpful in my current project, so thank you very much for all of your work on it.

I am trying to encode a video at a framerate lower than my application framerate. As an example I want to be able to have the game run at 60fps, but record the video at 15fps.

So I only want to send a frame to the encoder every 4th update. However it seems that CameraCapture.cs is written to push a frame every single update, since the project was intended to capture video at the same framerate as the application.

I tried rewriting the update function of CameraCapture.cs to this:
`void Update()
{
    var camera = GetComponent<Camera>();

    // Lazy initialization
    if (_session == null)
    {
        // Give a newly created temporary render texture to the camera
        // if it's set to render to a screen. Also create a blitter
        // object to keep frames presented on the screen.
        if (camera.targetTexture == null)
        {
            _tempRT = new RenderTexture(_width, _height, 24, GetTargetFormat(camera));
            _tempRT.antiAliasing = GetAntiAliasingLevel(camera);
            camera.targetTexture = _tempRT;
            _blitter = Blitter.CreateInstance(camera);
        }

        // Start an FFmpeg session.
        _session = FFmpegSession.Create(
            gameObject.name,
            camera.targetTexture.width,
            camera.targetTexture.height,
            _frameRate, preset
        );

        _startTime = Time.time;
        _frameCount = 0;
        _frameDropCount = 0;

    }

    if (isDirty)
    {
        _session.PushFrame(camera.targetTexture);
        _frameCount++;
        isDirty = false;
    }
}`

Where another script is setting the "isDirty" variable every 4th frame.

However I get this warning when trying to record:
`GPU readback error was detected.
UnityEngine.Debug:LogWarning(Object)
FFmpegOut.FFmpegSession:ProcessQueue() (at Assets/FFmpegOut/Runtime/FFmpegSession.cs:186)
FFmpegOut.FFmpegSession:PushFrame(Texture) (at Assets/FFmpegOut/Runtime/FFmpegSession.cs:55)
FFmpegOut.CameraCapture:Update() (at Assets/FFmpegOut/Runtime/CameraCapture.cs:180)`

and I get a 1kb video file.

Do you know what could be causing this issue? Is there any way to send a render texture to the encoder on demand, where it does not have to be every frame?

**Comment by keijiro** [comment]
FFmpegOut uses the GPU readback feature where the buffer has only a single frame capacity. It means that readback results will be lost if you don't process them every frame.

I guess that you probably can solve the issue by manually calling `ProcessQueue`.

1. Modify the following line to make `ProcessQueue` public.

https://github.com/keijiro/FFmpegOut/blob/master/Assets/FFmpegOut/Runtime/FFmpegSession.cs#L156

2. Call `ProcessQueue` when `isDirty` is false.

**Comment by sam598** [comment]
Thanks! That did the trick.

A simpler change that has the same result would be:

`if (isDirty)
{
    _session.PushFrame(camera.targetTexture);
    _frameCount++;
    isDirty = false;
}
else
{
    _session.PushFrame(null);
}`
