### ISSUE TITLE
Nvidia HEVC stalling at high resolutions

### ISSUE THREAD

**Issue by sam598** [keijiro/FFmpegOut#40]
So this isn't really an issue, it's more of an experiment and very long question about what the plugin is capable of.

I am trying to push realtime video encoding with the Nvidia HEVC codec to it's absolute max.

I'm having the Unity application run as fast as possible and I'm encoding frames at a constant rate using an "isDirty" flag (I'm using this modification https://github.com/keijiro/FFmpegOut/issues/39 from a previous question I posted).

On an RTX 2080 I am able to capture either 5120x4320@7.5fps, 3392x2880@15fps, or 2560x2160@30fps. By my estimate this pipeline is pushing and encoding about 140-160 million pixels per second.

In editor the application is running at about 400 fps and I am able to record without dropping a single frame. So far so good.

If i try to raise it to a 3392x2880@30fps, or a 5120x4320@15 fps (about 290-330 million pixels per second) the pipeline begins to stall.

In editor the application framerate drops to around 10-20 fps and it's dropping about every other frame.  When not recording the scene runs at 700fps when rendering at 5120x4320.

Specifically it's line 56 of FFmpegPipe.cs that is causing the stall:
`while (_pipeQueue.Count > 4) _pipePong.WaitOne();`

Nvidia claims that the RTX GPUs are capable of encoding 8k video, but I'm not sure if they specifically say it can encode 8k video in realtime.

Encoding 160 million pixels in a second is already pretty mind boggling, so I wouldn't be surprised if the hardware encoder is limited to around 200 million pixels per second.

I realize this is an absurd experiment and that this plugin wasn't meant for interactive or realtime capture. I just wanted to double check and make absolutely sure there wasn't something else in the pipeline that could be causing this slow down. 

Thanks again for your time and help with the previous question.

**Comment by keijiro** [comment]
I'm not sure if FFmpeg Nvidia encoder is optimized for 8k videos. First of all, I'd recommend testing it from the command line.

I also think that the length of `_pipeQueue` should be extended for this situation. Try changing `4` in line 56 of `FFmpegPipe.cs` to `8` or `16`. It requires tons of memory, but it makes sense in this specific application.

**Comment by sam598** [comment]
Hi Keijiro, thank you so much for the recommendations.

I had tried increasing the pipe queue size to 16, and even to 64. It still hit the same bottleneck, just at different frequencies.

When using the ffmpeg.exe provided with the plugin in command line, I tested transcoding 30 seconds of video at 30fps at different resolutions and got the following results:

h264_nvenc to hevc_nvenc:

3840x2160 takes 13 seconds
fps= 71 q=27.0 Lsize=   40278kB time=00:00:29.96 bitrate=11010.9kbits/s speed=2.38x

3392x2880 takes 16 seconds
fps= 61 q=27.0 Lsize=   41652kB time=00:00:29.96 bitrate=11386.5kbits/s speed=2.02x

hevc_nvenc to hevc_nvenc (h264_nvenc does not support greater than 4k resolution):

5120x4320 takes 34 seconds
fps= 27 q=27.0 Lsize=   73533kB time=00:00:29.96 bitrate=20101.6kbits/s speed=0.901x

7680x4320 takes 50 seconds
fps= 18 q=27.0 Lsize=  110068kB time=00:00:29.96 bitrate=30089.2kbits/s speed=0.604x

So while an RTX 2080 cannot do 8k in realtime it gets surprisingly close. It's clear that ffmpeg on it's own is performing better than in the plugin.

**Comment by sam598** [comment]
My next thought was that it could be a limit with how many bytes Unity can send to ffmpeg in realtime. Then I remembered that the plugin is sending RGBA images to ffmpeg, which then converts it to YUV420p.

So I wrote an image effect shader that converts an RGBA32 texture into a packed YUV420p texture:

`
// RGB to YUV conversion taken from: https://www.fourcc.org/fccyvrgb.php
// The rest of the shader is granted under an MIT license: https://opensource.org/licenses/MIT
Shader "Hidden/YUV420"
{
    Properties
    {
        _MainTex ("Texture", 2D) = "white" {}
    }
    SubShader
    {
        // No culling or depth
        Cull Off ZWrite Off ZTest Always

        Pass
        {
            CGPROGRAM
            #pragma vertex vert
            #pragma fragment frag

            #include "UnityCG.cginc"

            struct appdata
            {
                float4 vertex : POSITION;
                float2 uv : TEXCOORD0;
            };

            struct v2f
            {
		float2 uv : TEXCOORD0;
                float2 uvY : TEXCOORD1;
		float2 uvU1 : TEXCOORD2;
		float2 uvU2 : TEXCOORD3;
		float2 uvV1 : TEXCOORD4;
		float2 uvV2 : TEXCOORD5;
                float4 vertex : SV_POSITION;
            };

	    sampler2D _MainTex;
	    float4 _MainTex_TexelSize;

            v2f vert (appdata v)
            {
		float rowOffset = _MainTex_TexelSize.y * (2.0 / 3.0);
                v2f o;
                o.vertex = UnityObjectToClipPos(v.vertex);
		o.uv = v.uv;
		o.uvY = float2(v.uv.x, v.uv.y * (1.5 / 1.0) - 0.5);
		o.uvU1 = float2(v.uv.x * 2.0, v.uv.y * (1.5 / 0.25) - 1.0 + rowOffset);
		o.uvU2 = float2(v.uv.x * 2.0 - 1.0, v.uv.y * (1.5 / 0.25) - 1.0 - rowOffset);
		o.uvV1 = float2(v.uv.x * 2.0, v.uv.y * (1.5 / 0.25) + rowOffset);
		o.uvV2 = float2(v.uv.x * 2.0 - 1.0, v.uv.y * (1.5 / 0.25) - rowOffset);
                return o;
            }

            fixed4 frag (v2f i) : SV_Target
            {
				float2 uv = i.uv;
				if (uv.y < (1.0 / 3.0)) {
					if (uv.y < (0.5 / 3.0)) {
						// Is V
						if (uv.x < 0.5) {
							uv = i.uvV1;
						}
						else {
							uv = i.uvV2;
						}
						fixed4 col = tex2D(_MainTex, uv);
						float v = (0.439 * col.r) - (0.368 * col.g) - (0.071 * col.b) + 0.5;
						return v;
					}
					else {
						// Is U
						if (uv.x < 0.5) {
							uv = i.uvU1;
						}
						else {
							uv = i.uvU2;
						}
						fixed4 col = tex2D(_MainTex, uv);
						float u = -(0.148 * col.r) - (0.291 * col.g) + (0.439 * col.b) + 0.5;
						return u;
					}
				}
				else {
					// Is Y
					uv = i.uvY;
					fixed4 col = tex2D(_MainTex, uv);
					float y = (0.257 * col.r) + (0.504 * col.g) + (0.098 * col.b) + 0.0625;
					return y;
				}
            }
            ENDCG
        }
    }
}
`

This shader could be better optimized, but it gets the job done. The destination texture has the same width as the source, the height is 1.5 times taller, and the RenderTextureFormat is R8.

Preprocessing the YUV420p image accomplishes three things.

1) The pipeline is now moving 0.375 times less data off of the GPU and into ffmpeg.
2) It handles the RGB to YUV conversion on the GPU so ffmpeg doesn't have to.
3) It separates the image into planar Y, U and V images, instead of an interlaced RGBA image that ffmpeg would have to separate.

There are several different output pixel formats in your plugin, so I don't know the best way or if it is even necessary to integrate this shader. But this shader is free to anyone who wants to use it.

After making this change the bottle neck was removed and I got much better performance.

hevc_nvenc on an RTX 2080:

- 3840x2160 encodes at 30fps
- 3392x2880 encodes at 30fps
- 5120x4320 encodes at 15fps
- 7680x4320 encodes at 15fps
