### ISSUE TITLE
Paths containing spaces aren't allowed

### ISSUE THREAD

**Issue by forestrf** [keijiro/FFmpegOut#41]
This is probably because the complete path where the video is saved isn't in between `"` characters, so spaces break the arguments in the command line.

**Comment by keijiro** [comment]
I assume this issue is actually happened with FFmpegRecorder, not FFmpegOut. Anyway, I fixed the issue on the both sides. Now both FFmpegOut and FFmpegRecorder allow using filenames containing white spaces.

**Comment by keijiro** [comment]
I'm closing this issue. Please feel free to reopen it if it still reproduces.
