### ISSUE TITLE
Change recording path at runtime via scripting

### ISSUE THREAD

**Issue by panoramix32** [keijiro/FFmpegOut#46]
I would like to manually start and stop a recording session in different output paths set within a script. Is it possible to do it? thank you!

**Comment by keijiro** [comment]
You can change the path by modifying lines around here:

https://github.com/keijiro/FFmpegOut/blob/master/Assets/FFmpegOut/Runtime/CameraCapture.cs#L149

I'd rather recommend creating a new custom script based on CameraCapture.cs.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen for further problems.
