### ISSUE TITLE
Can add the ability to output video streams ？

### ISSUE THREAD

**Issue by GREAT1217** [keijiro/FFmpegOut#47]

**Comment by Ariel-Feldman** [comment]
You can change the string in the FFMpegSession class
int the returning string, instead of **outputPath** you can change it to FFMpeg stream commands...
works like a charm!

FFMpegSession.cs
{
    public sealed class FFmpegSession : System.IDisposable
    {
        #region Factory methods
.
.
.
            return new FFmpegSession(
                "-y -f rawvideo -vcodec rawvideo -pixel_format rgba"
                + " -colorspace bt709"
                + " -video_size " + width + "x" + height
                + " -framerate " + frameRate
                + " -loglevel warning -i - " + preset.GetOptions()
                //+ " \"" + outputPath + "\""
                + " -f h264 udp://192.168.y.yy:xxxx"
            );
     }

**Comment by keijiro** [comment]
Thanks for the answer. Closing.

**Comment by GREAT1217** [comment]
thanks for your answer!

**Comment by lchunleo** [comment]
hi @GREAT1217 , i have tried it but mine can't work. i am running the unity to run it up and using vlc to view the udp stream.

return new FFmpegSession( "-y -f rawvideo -vcodec rawvideo -pixel_format rgba"
            + " -colorspace bt709"
            + " -video_size " + width + "x" + height
            + " -framerate " + frameRate
            + " -loglevel warning -i - " + preset.GetOptions()
            //+ " "" + outputPath + """
            + " -f h264 udp://127.0.0.1:8554"

and in the vlc, i typed  udp://127.0.0.1:8554 , the vlc is not showing up anything.

any advise? thank you
