### ISSUE TITLE
3rd recording instance doesn't work. 

### ISSUE THREAD

**Issue by harrywenjie** [keijiro/FFmpegOut#48]
I made a Unity demo to output an short animation with FFmpegout. Each game instance would output one file then close byitself.  Now when I open three instances,  the 3rd one opens but FFmpeg attach to it would close by itself. The 3rd file would be empty?

Could it be that FFmpeg refuse to run more than two instances?

**Comment by keijiro** [comment]
I don't think there is any particular reason why the third FFmpeg instance fails. It should work.

**Comment by harrywenjie** [comment]
I found how. if I choose a preset with nvdia in it like HEVCnvdia, it won't open 3rd instance. The log says out of memory. But the default HEVC works just fine.

**Comment by keijiro** [comment]
Thanks for the information. It makes sense. I haven't realized that there is such a problem. I'll consider adding it as a test case.
