### ISSUE TITLE
5.6.0.f3 error

### ISSUE THREAD

**Issue by nbac** [keijiro/FFmpegOut#5]
RenderTexture.Create: Depth|ShadowMap RenderTexture requested without a depth buffer. Changing to a 16 bit depth buffer.

i do use post processing stack on the camera as well  the capturing looks really weird

**Comment by keijiro** [comment]
Thanks for reporting it. Could you provide a minimum project that can reproduce the issue?

**Comment by nbac** [comment]
ill check if i can reproduce it something else pops up
Project's default behavior is set to 3D and does not contain packable sprites. Spent 5.45 seconds searching for sprites. Consider setting sprite packing mode to 'Disabled' or 'Enabled for Builds' under Project -> Editor -> Mode to speed up entering Playmode.
than capture started
than RenderTexture.Create: Depth|ShadowMap RenderTexture requested without a depth buffer. Changing to a 16 bit depth buffer.
than
Capture ended (Cam_shot_01_2017_0411_092220.mp4)
UnityEngine.Debug:Log(Object)
FFmpegOut.CameraCapture:ClosePipe() (at Assets/FFmpegOut/CameraCapture.cs:170)
FFmpegOut.CameraCapture:OnDisable() (at Assets/FFmpegOut/CameraCapture.cs:60)
UnityEngine.GameObject:SetActive(Boolean)
Manager:HideCameras() (at Assets/Manager.js:19)
Manager:Camera2Switch() (at Assets/Manager.js:30)

i have multiple cameras and i do siwtch them with animation events    could that cause the problems?

**Comment by keijiro** [comment]
> i have multiple cameras and i do siwtch them with animation events could that cause the problems?

Hmm, it depends on the case... but yes, could be problematic.

**Comment by keijiro** [comment]
I think this issue doesn't reproduce on the latest version. Closing.

Please feel free to reopen this ticket when you meet further problems.
