### ISSUE TITLE
Make Button to Start Recording

### ISSUE THREAD

**Issue by Schaamhahr** [keijiro/FFmpegOut#50]
Hello, 

I wanted to know if there is any way that the script won´t start directly after pressing play, cause in my case i need it to start when i press a button. 

Thanks in advance!

**Comment by keijiro** [comment]
The CameraCapture script doesn't start recording if it's disabled, so make them disabled on Editor, then enable it from a script.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.
