### ISSUE TITLE
Support for Server build

### ISSUE THREAD

**Issue by chungvmo** [keijiro/FFmpegOut#54]
I have plan for build and run on linux server for without GPU card, I trying with currently code not working. Do you have any idea for it?, I'm programmer and I can support

**Comment by keijiro** [comment]
As I note on README.md, FFmpegOut on Linux requires Vulkan. If the server supports Vulkan, it should work.

**Comment by chungvmo** [comment]
> As I note on README.md, FFmpegOut on Linux requires Vulkan. If the server supports Vulkan, it should work.

Thanks for reply. I know we can record on linux with graphic but my plan is run on cloud server without graphic card(use "Server Build" option in Unity Build option)

**Comment by keijiro** [comment]
It requires Vulkan, so it requires a graphic card too.

**Comment by chungvmo** [comment]
> It requires Vulkan, so it requires a graphic card too.

Thanks. I will close issue. Maybe I will have some research for implement without GPU card or run on cloud server with GPU card.
Have a night day!
