### ISSUE TITLE
Failed to initialize an FFmpeg session due to missing executable file. Please check FFmpeg installation.

### ISSUE THREAD

**Issue by Aleafleave** [keijiro/FFmpegOut#58]
Failed to initialize an FFmpeg session due to missing executable file. Please check FFmpeg installation.
Mac

**Comment by keijiro** [comment]
Did you install FFmpegOutBinaries package?

**Comment by Aleafleave** [comment]
When install FFmpegOutBinaries package, initialize successful.
Thank you.
