### ISSUE TITLE
FFMpegout UWP App Unity Build

### ISSUE THREAD

**Issue by astaikos316** [keijiro/FFmpegOut#59]
I am wondering if there is a way to get this to work with a Unity UWP application build.  I have a requirement to run in UWP and I know that pipes aren't supported.  Has anyone looked at this issue previously?

**Comment by keijiro** [comment]
FFmpegOut doesn't support UWP. My understanding is that it's not technically possible.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.
