### ISSUE TITLE
VR issues

### ISSUE THREAD

**Issue by kornellvarga** [keijiro/FFmpegOut#6]
Hi Keijiro,

As I have said before, amazing work as always!!
I have been running some tests, now with VR. I am using the built in OpenVR API to run my HTC Vive.
The recording blocks the HMD position and rotation tracking as well as displaying back the image to the headset. Currently I am using the script directly on the camera of the HMD, but I ll get back to you with a test where I put another camera only for the recording, that might be a good temporary solution.

**Comment by keijiro** [comment]
Thanks for the feedback. Unfortunately, as I wrote in README, FFmpegOut is not recommended to use in an interactive application. It slows down the application significantly in most cases, and it's an intentional design. The main scope of this plugin is for pre-rendering in a non-interactive way.

**Comment by kornellvarga** [comment]
yes, understood that. however I don't really see any other neat way currently to approach a potential live recording.
Do you think that the complete blockage of the position & rotation tracking of the Vive roots in the intentional design?
Anyway,  I think I ll just tinker with the code to see if I can achieve an acceptable result, probably the separate camera solution is the way to go.

**Comment by daseyb** [comment]
I also got the previous version to an acceptable frame rate by moving the
ffmpeg pipe to a different thread and writing out frames asynchronously.

I'll let you know when I get around to integrating the current version.

**Comment by kornellvarga** [comment]
yep, thats the thought Ive been toying with too :)

**Comment by keijiro** [comment]
I added issue #10 ("Multithreading support") to the tracker. Now I'm closing this ticket because the main topic of the current discussion is not relevant to the original topic ("VR issues"). Please feel free to reopen the ticket when you meet further problems with VR.
