### ISSUE TITLE
audio reorder

### ISSUE THREAD

**Issue by chaserat** [keijiro/FFmpegOut#60]
I use ffmpegout in ubuntu 18.04. After getting the video, I found there is no audio information in the video. Does it support audio capture and save it in the ".mp4" file with video? Or any complement measures can be help in ubuntu?

**Comment by keijiro** [comment]
FFmpegOut only supports video recording. You can't record audio outputs.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.
