### ISSUE TITLE
How to change path file, name file and stop recording scripting?

### ISSUE THREAD

**Issue by IrvingMaciasV** [keijiro/FFmpegOut#66]
Hi can someone please can told me how to change or where in the script I can change the Path that de file is saved and the name of the file?
Also if there is any form to stop/play the recording in a certain time or action?

**Comment by keijiro** [comment]
> Hi can someone please can told me how to change or where in the script I can change the Path that de file is saved and the name of the file?

https://github.com/keijiro/FFmpegOut/blob/master/Assets/FFmpegOut/Runtime/FFmpegSession.cs#L21

> Also if there is any form to stop/play the recording in a certain time or action?

You should write a control script.

**Comment by IrvingMaciasV** [comment]
Thanks. Where is the script of the pathfile (where is saved the video)?
