### ISSUE TITLE
 FFmpegOut for linux

### ISSUE THREAD

**Issue by Reetikajain68** [keijiro/FFmpegOut#67]
Is FFmpegOut compatible with Linux ? 
If yes , why it is giving this error - "**failed to initialize an FFmpeg session due to lack of async GPU readback support. Please try changing graphics API to readback-enabled one**." ?

Please help or suggest any other tool / plugin which can record screen on linux in unity gameplay.

**Comment by keijiro** [comment]
It means you should use Vulkan instead of OpenGL.

**Comment by keijiro** [comment]
I'm closing this issue now. Please reopen it for further problems.

**Comment by Reetikajain68** [comment]
I have tried both Vulkan and OpenGL. Still this issue occurs. What else i can try ?

**Comment by keijiro** [comment]
That's weird. Could you try the following sample project? It uses the same feature and should run on Vulkan.

https://github.com/keijiro/AsyncCaptureTest

**Comment by Reetikajain68** [comment]
I am trying to run this on Oracle VM Virtual Box. It's supports on linux , Right ?

**Comment by Reetikajain68** [comment]
![image](https://user-images.githubusercontent.com/85737199/150501169-dce0b686-2eba-4d61-abb4-981b661aee17.jpeg)

Thanks, I am trying to run this on Oracle VM Virtual Box. Please check the result.

**Comment by keijiro** [comment]
> It's supports on linux , Right ?

It's hard to say yes/no. Unity Editor doesn't officially support a system on an emulation layer (see the system requirement page), but *it just works* and most people are okay with it. However, this feature (async GPU readback) is one of advanced graphics features, and I guess most emulation layers don't support it properly.

I'd recommend using a Linux system without emulation, or simply using UnityRecorder instead. There is no advantage in this package over UnityRecorder.

**Comment by keijiro** [comment]
I'm re-closing this issue now. Please reopen it for further problems.
