### ISSUE TITLE
No channel layout for input 1

### ISSUE THREAD

**Issue by stonebirdarchitect** [keijiro/FFmpegOut#68]
While attempting to record a video in the project, it throws error "No channel layout for input 1". What would cause this issue and what are the ways around it ?

```
for (int i = 0; i < audioFileName.Length; i++)
{
    audioInput += " -stream_loop -1 -i " + audioFileName[i];
    inputArgs += "[" + (i + 1) + ":a]";
}
var parameters = "-y -f rawvideo -vcodec rawvideo -pixel_format rgba" +
                 " -colorspace bt709" +
                 " -video_size " + width + "x" + height +
                 " -framerate " + frameRate +
                 " -loglevel warning -i -" + audioInput +
                 " -filter_complex \"" + inputArgs +
                 "amerge=inputs=" + audioFileName.Length +
                 "[a]\" -map 0:0 -map \"[a]\" -c:a aac -ac 2 -t " +
                 duration + "ms "
                 + preset.GetOptions()
                 + " \"" + outputPath + "\"";
return new FFmpegSession(parameters);
```

**Comment by keijiro** [comment]
What is this code snippet? There is no such section in this project.

**Comment by stonebirdarchitect** [comment]
@keijiro That's the call to FFmpegSession with given parameters. I'm not sure what could possibly cause this error, whether it's something about the call, or the audiofile itself.

**Comment by keijiro** [comment]
Honestly, I have no idea. I can't guess anything from this short snippet.

**Comment by stonebirdarchitect** [comment]
Do you have any ideas on what could cause this warning/error at all ?

> FFmpeg returned with warning/error messages. See the following lines for details:
> [Parsed_amerge_0 @ 000001953174e800] No channel layout for input 1

**Comment by keijiro** [comment]
Unfortunately, I have no idea -- I'm not a specialist of ffmpeg. I'd recommend asking a specialist to solve your problem.

**Comment by keijiro** [comment]
I'm closing this issue now as the original post is not relevant to this project. Please reopen it for further problem.
