### ISSUE TITLE
Recording video from screen and adding audio to the recording in one move

### ISSUE THREAD

**Issue by stonebirdarchitect** [keijiro/FFmpegOut#69]
Is there a nice way to do it without freezing Unity for several decades? 
There's a list of arguments that will allow the user to record the screen, there's a different list of commands (thanks issue #29) that will allow the user to record the audio from the file to a .mp4 file, but when combined Unity (or more specifically ffmpeg.exe) just loses its will to live and freezes. Any suggestions on how to tackle this?

Edit: I've also tried to simply put the audio clip in the scene and record the scene audio, but it's recorded with a short but noticeable audio stuttering in the beginning. More specifically audio begins recording after the video does, and blankness causes stuttering for some reason (video was recording for 13 seconds, audio for 10 seconds, and they both stopped at the same time, through forcible application exit).

**Comment by keijiro** [comment]
Unfortunately, I have no idea about his modification. My opinion is that it's impossible to record videos stably with audio in Unity. Someone may be able to make it possible, but sadly, it's not me. I'd recommend asking him for further advice.
