### ISSUE TITLE
unable to get it working in osx

### ISSUE THREAD

**Issue by olgv** [keijiro/FFmpegOut#7]
Running the test scene after copying the FFmpeg binary executables in the right folders, makes the console scream...
`Win32Exception: ApplicationName='/Users/neutral90/Desktop/FFmpegOut/Assets/StreamingAssets/FFmpegOut/OSX/ffmpeg', CommandLine='-y -f rawvideo -vcodec rawvideo -pixel_format rgb24 -video_size 1280x720 -framerate 30 -loglevel warning -i - -c:v prores_ks -pix_fmt yuv422p10le Main_Camera_2017_0412_121855.mov', CurrentDirectory=''
System.Diagnostics.Process.Start_noshell (System.Diagnostics.ProcessStartInfo startInfo, System.Diagnostics.Process process)
System.Diagnostics.Process.Start_common (System.Diagnostics.ProcessStartInfo startInfo, System.Diagnostics.Process process)
System.Diagnostics.Process.Start (System.Diagnostics.ProcessStartInfo startInfo)
FFmpegOut.FFmpegPipe..ctor (System.String name, Int32 width, Int32 height, Int32 framerate, Codec codec) (at Assets/FFmpegOut/FFmpegPipe.cs:39)
FFmpegOut.CameraCapture.OpenPipe () (at Assets/FFmpegOut/CameraCapture.cs:133)
FFmpegOut.CameraCapture.Update () (at Assets/FFmpegOut/CameraCapture.cs:79)
`
...about 177 times.

Unity 5.6.0f3, OS X 10.11.6

**Comment by keijiro** [comment]
I guess that the executable permission is missing from the binary. You have to `chmod a+x ffmpeg` or something like that.

Or try the release package. It contains ffmpeg binaries so that you don't have to copy them manually.

https://github.com/keijiro/FFmpegOut/releases

**Comment by olgv** [comment]
Indeed, the ffmpeg had to be `chmod +x` 'd.
Thank you
