### ISSUE TITLE
Recording a .webm video to .mp4 results in sped up videos

### ISSUE THREAD

**Issue by jml0123** [keijiro/FFmpegOut#70]
Hi, we are using this plugin to record `.webm` video textures in Unity and saving as an `.mp4.` For some reason, the resulting mp4 files are a lot faster than the original video files (~2x faster). I am setting the camera capture framerate to the source frame rate, so I'm not sure why the timing is still off.

Here's a warning that was logged:
`Significant frame dropping was detected. This may introduce time instability into output video. Decreasing the recording frame rate is recommended.
`

It's super important that the framerate of the output video matches the video source framerate, as events are triggered based on source video timestamps.

Thanks for the help!

**Comment by keijiro** [comment]
This package is not maintained. Migrating to Unity Recorder is strongly recommended.

https://docs.unity3d.com/Packages/com.unity.recorder@4.0/manual/index.html

**Comment by jml0123** [comment]
Hi @keijiro, thanks for the tip. However, we need to use a recorder that works in a packaged build, not just in Unity Editor. If the problem persists, we can look for a different recording solution.

**Comment by keijiro** [comment]
There is also license issue. Is it okay to apply GPL to your product?

> we can look for a different recording solution.

Yes, it's recommended to look for another solution.

**Comment by jml0123** [comment]
We are trying a few solutions with this package before moving on. Is it possible to dynamically set the FrameRateController's frameRate property? Seems like this is inaccessible. I've tried to access it but it is not recognized:
<img width="444" alt="Screen Shot 2022-08-10 at 3 33 25 PM" src="https://user-images.githubusercontent.com/29313716/184034763-733bb6c2-f5af-4f32-86bd-665b716135e8.png">
<img width="548" alt="Screen Shot 2022-08-10 at 3 30 55 PM" src="https://user-images.githubusercontent.com/29313716/184035623-20862617-cabb-47a5-8d16-83252cb8d01b.png">


I am trying to set it in another script, which leads to the error:
<img width="810" alt="Screen Shot 2022-08-10 at 3 32 43 PM" src="https://user-images.githubusercontent.com/29313716/184035420-9ed59298-2f7b-4a16-bb0d-29e9639d993f.png">
<img width="1239" alt="Screen Shot 2022-08-10 at 3 32 58 PM" src="https://user-images.githubusercontent.com/29313716/184034952-328c30cf-7d5b-4adc-b74c-1fee4eaec4cb.png">

**Comment by keijiro** [comment]
`FrameRateController` is just a utility script. You can easily extend it by copying it into your project.

**Comment by keijiro** [comment]
I'm closing this issue now. Please reopen it for further problems.
