### ISSUE TITLE
Error on import: 'DynamicMethod' could not be found

### ISSUE THREAD

**Issue by equizo** [keijiro/FFmpegOut#71]
FSR 1.5
Unity 2020.3.27

`Library\PackageCache\com.handzlikchris.fastscriptreload@5f73a1ba43\Scripts\Runtime\AssemblyChangesLoader.cs(189,57): error CS0246: The type or namespace name 'DynamicMethod' could not be found (are you missing a using directive or an assembly reference?)
`

**Comment by keijiro** [comment]
Please ask the author of com.handzlikchris.fastscriptreload. The error is thrown from it.
