### ISSUE TITLE
Camera view flips ingame after recording with Set resolution true

### ISSUE THREAD

**Issue by Sh1rogane** [keijiro/FFmpegOut#8]
Hi!

I found a problem with that the camera view will flip and lose anti aliasing after recording with Set resolution is set to true. It works correctly if Set resolution is set to false.

I have tested this in a new project with only this added and it stills happens.
If I disable the CaptureCamera script after recording it flips back correctly but the anti aliasing is still missing.

**Comment by keijiro** [comment]
Thanks for reporting. Actually this is a known issue of Unity 5.6.0.

https://issuetracker.unity3d.com/issues/setting-rendertexture-to-null-when-post-processing-behaviour-is-enabled-flips-game-view-vertically-while-renderingpath-equals-forward

Please wait for the next patch release.

**Comment by jlind93** [comment]
Tested again with the new patch 5.6.0p4 and the problem is gone now.

**Comment by Sh1rogane** [comment]
Tested again with the new patch 5.6.0p4 and that solved the issue.
