### ISSUE TITLE
Not working with KinoBloom

### ISSUE THREAD

**Issue by guiray** [keijiro/FFmpegOut#9]
When I have both FFmpegOut + [KinoBloom](https://github.com/keijiro/KinoBloom), there is some weird things happening. It looks like a feedback effect and horizontal mirror.

Original scene (with KinoBloom):
![originalscene](https://cloud.githubusercontent.com/assets/19233693/26286225/fb87de80-3e2d-11e7-82e9-2f91c3efbef8.PNG)

With FFmpegOut:
![withkino](https://cloud.githubusercontent.com/assets/19233693/26286226/fb8b1e56-3e2d-11e7-9082-dbc0160102df.PNG)

Unity 5.6.0
Windows 10

**Comment by keijiro** [comment]
Could you try turning off "Set Resolution"?

**Comment by guiray** [comment]
"Set Resolution" was Off. But the effect is the same when it is On.

**Comment by keijiro** [comment]
Sure. Thanks for the confirmation. Could you provide a minimal project that reproduces the issue?

**Comment by guiray** [comment]
There you go 😊
https://github.com/guiray/FFmpeg-Out-and-KB-test-project

**Comment by keijiro** [comment]
I suppose that this issue doesn't reproduce with the latest version.

https://github.com/keijiro/FFmpegOut/releases/tag/v1.0.0

Please feel free to reopen if it still reproduces.
